apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rapid
  namespace: rapid  #Ensure this namespace exists
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-rapid
  template:
    metadata:
      labels:
        app: demo-rapid
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000  #Ensuring it aligns with `runAsUser`
        fsGroup: 1000  #Ensures correct file system permissions inside the container
        seccompProfile:
          type: RuntimeDefault  # Apply seccomp at pod level
      containers:
        - name: demo-rapid
          image: r-f54d-rapid-docker-local.artifactory.2b82.aws.cloud.airbus.corp/nginx-test:1.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault  # Ensures security sandboxing
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      imagePullSecrets:
        - name: airbus  #Ensure this secret exists in the "rapid" namespace
