apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-rapid-ingress
  namespace: rapid
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: demo.rapid.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-rapid-svc
                port:
                  number: 80  # Service must listen on HTTP, since Nginx terminates HTTPS
  tls:
    - hosts:
        - demo.rapid.com
      secretName: demo-rapid-tls
